# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fP/eqfyjZuZTFsCfQeaJrJ94//Gj/9Qxeb6pTs8=,iv:aInDEwu+8c1bZPMeNWKzfcJfbvk48nIqzuU9PDsBmx4=,tag:V5sB55d1cQJNUIxrwzd2Dw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:6VqgXlM0KCAsav8RWMq/XOOnZIe0z77g006rWHlEE24A2KqTVw==,iv:5DfOaPDXz7X6d8wtus48vRmVSRbRw6AqasuQW/Q2MuQ=,tag:f4nPptdjgpH9vOp18y7Smg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:xdbb2bUERjkURPfZYyGwSkFr/DXM,iv:PKSxohY7cgLS5hNQcMtdhtLrodmWuzZiEPlkRMYW75c=,tag:kRl2aUBtqfeDqFbNzSUCEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdapdgc8jy47q354dmp9988fpl26xfvjknglp3r7ska0q8wpcsgq8vd96v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSXZXdW1GT242ek4zLyta
            UDNuQm5jcEgwY0FVTWVINVVUUkpIZUFxTEF3CkJDMmFQTW1FeTRsSlNuQ2VVdlhy
            UWQ0UVBKdHBhZDUxbTJIOUg5ZTdPVG8KLS0tIGJXVlc0MUFWUTRwUWhnZ0hOeGRC
            cUhYTjJINzFwKzRtdC9OZVFURVk5bmsKKY/glAurSI4h/f+9sOHT+ifvc84ipxh+
            s8sj0VE+klYpyMNJry1JYMZpqVrU3lUxaB2otYFQBSAYJCtkTFx3Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-16T20:11:08Z"
    mac: ENC[AES256_GCM,data:liE1mJhAD+HLOfcpxUQbE5xua44NkrvipeecfZcz3dAFcVN5Q7EslNgJApikNq6/3ot5S5F6oM8d2TsSoC8OY2vhYl4IW/HsnBcS2ZKM4abxGz7zQrikgvIcOkLlz5og8HwbKBLqs/sEauiD2gMh+fVvNuCOhu9+02GaVD2vRTs=,iv:ZZFd8yWFT5dIh3yt0xWs4rsGpMiSH7hC5dgJ7z06WL8=,tag:6JKizZfHOeKPhyeZuACwpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
