# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:myWtDBAn5Pb1xDdThHJM+fkh6/78IXyp5j4Ztjw=,iv:dV7fjyQmfCECfWyAJaWxN3UkUq8miI8KhT8NbwdTI78=,tag:lL0okbmvLK1vYOi/J5L4GQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:2z1f4HijdE6wy5JmrxVbdJCmdbAoc9KjteHdCLU5y+f5P8/H1A==,iv:eYm6uS0yCNuYtGt47QsF+tDbo5UBWXuQ+cz2xwgfgNk=,tag:kPAUuyew6h0yKPpXC48hnQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:d2LNY3vAybB5fD7FVAjpmgVVOXjT,iv:U6JoTv+Zm1QuJlkKSTo1zbXripRvbVHYZ05voePTKXc=,tag:wpwJVg7rXMaouc3L+uf8Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdapdgc8jy47q354dmp9988fpl26xfvjknglp3r7ska0q8wpcsgq8vd96v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdFBBNHVHVVR2QklITmFN
            VWVrOTBjYTNuMGU1YUcwT0ZsSmI5MEtySW1rCkk0dEVkYlZmaDZXTW9CUStwdFc3
            K290SWxML2xoMVN5bTZWY2ZxbmhRNzAKLS0tIFpDOTZkWDRqa3hHcDdSeFpWcFVV
            bU8wcnVkNFFGMW45QjQ2c3U3eWhyU3MKZOFYhhmbwTlsQMk0tigL4EL/e7SJC1oI
            eBoipZx1Ms21URmjTOifnBODXtKY2yPajpj56qASFuM0TDJxdzhXRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-01T14:12:54Z"
    mac: ENC[AES256_GCM,data:tjN44ieMcjpWW3zjiMb71K2Wviz6cUotzSDnpPcH86SeweBNhCkRY/7BHB7d26oos9dBd2gMjD3zF27FAMqsiNaCyYNUTdUFl9lf1f1A2NaeVCNLaTdldoRim8DdL6801o7+n5yr2uL0JBGq07++aGu5Cq4ssr/uE1M0RG7TGMY=,iv:R1/0ICQPTWPToeA7eozclUK+y72AA8YqLFqBUzxnWzA=,tag:rau+PrwRT/fcTgW+KclKQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
