---
kubernetes:
  children:
    master:
      hosts:
        hkb-president-0:
          ansible_host: 192.168.1.4
        hkb-president-1:
          ansible_host: 192.168.1.5
        hkb-president-2:
          ansible_host: 192.168.1.6
