# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:WV110E03xFe8fIePbmDE8ue857fUWYQVf5NLxEJKtkAZqikvLg==,iv:ff70RVt2q2XeL6GJT7jMmHHQRnJoJQlCXPrDpYKkGFY=,tag:9ZEhwcHl+gLhqduq6GWYqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdapdgc8jy47q354dmp9988fpl26xfvjknglp3r7ska0q8wpcsgq8vd96v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSDZDQ2JzVm5pM2FuZzlz
            ekpHamxDRjl1dS9Kb3pDUTJVQ2RBRllheVJVClBtVXhva2h5ZnlPL2x3WmZUb1Fa
            LzZEUkVsbE0vYkplaUhSamYxOHB3R28KLS0tIFFxS1Q4eDN1NjJJRGcwTDJvalFT
            dW5IRWNMQ2tNTkgyVDVYUEkvb2RSdWMKsA4yT+58sVZEi1Wgphmc1cAcs9Sh46R5
            qUTyNjN2s/qW2DN0bP0ktwDbDcsmIlNRQ0aWjqxkcJSVhSUfMbaOFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-16T20:11:08Z"
    mac: ENC[AES256_GCM,data:pFILROk1d1biCxbClrDHxmUCOuOLjSeaxmRIzxCBpkxicDWeXNv7rYi41x3HVfi7ASFfGym4+fCp0MIprBC/r/c2D/kER62UfaCN1o81whNeiDiLHoQkUeb8gb/oaz2voMFdx6l0psCRF4IBX8Ya7/o4Kgz9ZLNC+39VrQ2LitE=,iv:tevplaLriVHa//ko1sE17hYPlRM/wSkEmhMYK1oJgZg=,tag:/dyat2eorelhkP2rhpL4ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
