# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:HKikT/PzfFa50+RB5187u1qhDiiR+aLbmsyesQ5cQosoqy7bow==,iv:O5eQLeOlYo7jv1r2cQK9BUqS0BMQiCb+6zZoo3GczY8=,tag:9sYCxgzZrvSKpR/XzZ3LIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdapdgc8jy47q354dmp9988fpl26xfvjknglp3r7ska0q8wpcsgq8vd96v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV1dza25FOXZ0NXVacjFl
            alZnbFJUZmpnMHV0QktQSHJQRDZPSGxuWGlNCjFKU2dYZEJCM3U1VjZGY2xoOTdz
            RDJOMUphNlNUT1l1ZWszYmROQ2xNVmsKLS0tIFcxVWpOTHRSZ3ArYUV0T1FqekZM
            d3JENi9hcDdpOWllVy9qYlVVYWJUMGcKOB8JyKPF2gGGds/CVbWgFUFRVObJTja2
            5fJJ1SG+b67kNNMaXw/XS5cGvDFy2iMusnEg8H0tCPBngbVl7iKxow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-01T14:12:54Z"
    mac: ENC[AES256_GCM,data:NxQEx7aBeCScLEfCUOl0br+htH6L0DjR94M2QH492f7ofg1K0kulVA9cpTdjra2yjmOd5tqYGpmUvNtFER5xzuZPbYO92D+4yjZIAACvErPHrqN2aidEu0VdE46docpSfAf5j9RqI58LtOKvixSb1i/A/HAY93A4ZLXAmfwJKmk=,iv:7M3jNwZa+dnMW6Tx/zERcWkBUe9RRemY9Sp66AQQko0=,tag:GsxWGnc0AbBatMn1n7ypdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
